# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-16 06:09
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin_number', models.CharField(max_length=20)),
                ('current_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('model', models.CharField(max_length=200)),
                ('status', models.IntegerField(choices=[('1', 'Available'), ('2', 'Occupied'), ('3', 'Offline')])),
            ],
        ),
    ]
