# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-16 06:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_driver_phone'),
        ('cabs', '0002_auto_20180416_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='cab',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Driver'),
        ),
    ]
