# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-16 06:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='drives',
        ),
    ]
