# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-16 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_driver_drives'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='phone',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
